name: ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js to 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: yarn eslint src/**/*.ts

      - name: Run TypeScript
        run: yarn tsc --project tsconfig.json --noEmit
